### ISSUE TITLE
is adwaita theme incoming?

### ISSUE THREAD

**Issue by semi710** [eylles/pywal16-libadwaita#1]

**Comment by eylles** [comment]
Yes, this repo will ultimately have a main script to generate a gradience json file and build a kvantum template from a colorscheme file OR pywal colors.

that with the intention of coordinating colors AND style across gtk and qt.

**Comment by semi710** [comment]
> Yes, this repo will ultimately have a main script to generate a gradience json file and build a kvantum template from a colorscheme file OR pywal colors.
> 
> that with the intention of coordinating colors AND style across gtk and qt.

I have seen the screenshots, I liked them.
Just wanted to know you have a fork of pywal `pywal-16` what it does different?
And I have been using `wpgtk` that uses pywal as base and generate colors on template file.

So I am quite curious to know why you are taking the path for the `main` script instead of templates? Is it because then it will be easier to have custom lighten and darken function?

**Comment by ghost** [comment]
Haven't tried your version, but the actual kvlibadwaita has wrong tab appearance and the action buttons aren't properly colorized like in libadwaita (eg. default button, ok, destructive etc.). Also has wrong colors.

So it's not very usable. Could be a decent theme if that were fixed. @eylles

**Comment by eylles** [comment]
@developer91234 well i just templated what was there "manually" (using string replace in vim and adjusting), i want to improve the process to have the templating and building done programatically, but i would still be tied to however the kvantum theme is actually made and i don't know how to create a kvantum theme, if anyone can cobble a better matching kvantum theme i could template it on the same day for this.
