### ISSUE TITLE
Gtk theme top bar issue.

### ISSUE THREAD

**Issue by semi710** [eylles/pywal16-libadwaita#4]
Hey this is awesome <3
just noticed this while testing the project.
![image](https://github.com/eylles/pywal16-libadwaita/assets/60490474/c8854c23-c434-4445-9965-a544650042d8)
if some other window is focused then the window topbar is like this

when the window is in focused everything is fine.
![image](https://github.com/eylles/pywal16-libadwaita/assets/60490474/4a07975e-6223-4fa1-a7c5-5d094d409181)

**Comment by eylles** [comment]
yeh, that is the backdrop color, in the repo's template that is defined as color4, feel free to redefine it to whatever color you feel, i simply didn't know what color to define it as and on my setup it didn't make a difference for whatever reason (probably something to do with how awesome wm manages window focus not notifiying gtk3/4 properly or some interaaction with flatpak)

also i very much suggest using pywal16 with the --cols16 flag for better results, the default colorpalette is generated at 9 colors to maintain backwards compatibility with pywal and stuff that assumes 9 colors only.

**Comment by niksingh710** [comment]
Thanks for the suggestion.
Just want to ask, do you have template for qt5ct theme for qt based application?
And in kvantum the checkboxes are not visible.
